import { str } from "@workbench/protocol";
import type { GoldenSpec } from "@workbench/contract";

export const goldens: GoldenSpec[] = [
  { description: "integer literal", input: str("0") },
  { description: "negative integer", input: str("-5") },
  { description: "double negation", input: str("--7") },
  { description: "single variable", input: str("x") },
  { description: "underscored variable", input: str("var_1") },
  { description: "long identifier", input: str("alpha") },
  { description: "binary sum", input: str("x + y") },
  { description: "binary product", input: str("x * y") },
  { description: "binary difference", input: str("x - y") },
  { description: "binary quotient", input: str("x / y") },
  { description: "exponent", input: str("x^2") },
  { description: "right-assoc exponent", input: str("x^2^3") },
  { description: "precedence: + then *", input: str("a + b * c") },
  { description: "precedence: * then +", input: str("a * b + c") },
  { description: "precedence: ^ before *", input: str("a * b^2") },
  { description: "precedence: unary minus before ^", input: str("-x^2") },
  { description: "left-associative -", input: str("a - b - c") },
  { description: "parens", input: str("(a + b) * c") },
  { description: "nested parens", input: str("((x + 1))") },
  { description: "rational literal", input: str("3/4") },
  { description: "decimal literal half", input: str("0.5") },
  { description: "decimal literal eighth", input: str("0.125") },
  { description: "binomial expansion shape", input: str("(x + 1) * (x - 1)") },
  { description: "polynomial sum", input: str("x^2 + 2*x + 1") },
  { description: "polynomial difference", input: str("x^2 - 2*x + 1") },
  { description: "rational function", input: str("(x^2 - 1) / (x - 1)") },
  { description: "two variables", input: str("x*y + y*z") },
  { description: "three variables product", input: str("a * b * c") },
  { description: "leading whitespace", input: str("   x") },
  { description: "trailing whitespace", input: str("x   ") },
  { description: "interior whitespace", input: str("x  +   y") },
  { description: "tabs and newlines treated as whitespace", input: str("x\t+\ny") },
  { description: "deeply nested parens", input: str("(((x)))") },
];
