// =============================================================================
// bench/erf-anchor/oracles/wolfram/adapter.ts
//   Gold-tier Wolfram Mathematica oracle adapter for the Erf-family corpus.
// =============================================================================
//
// This script consumes `bench/erf-anchor/corpus.json` (the frozen 271-input
// manifest generated by `generate-corpus.ts`, ADR-0040 §"Decision 10",
// bead `scientist-workbench-9sqr`), evaluates each input against Wolfram
// Mathematica's arbitrary-precision implementation of the Erf family at 60
// decimal digits, and emits the canonical gold-tier golden-master file
// `bench/erf-anchor/oracles/wolfram/results.json`.
//
// Why this is the gold tier: Wolfram Mathematica is a closed-source
// commercial CAS with three decades of validation behind its special-function
// kernel; it is one of the two independent arb-prec voices (alongside mpmath
// 1.3.0, the only other locally-installed arb-prec engine — R5 §1 capability
// matrix). For the real branch, Boost.Math `cpp_bin_float<50>` provides an
// independent silver-tier cross-check. For the complex branch, Wolfram +
// mpmath is the entire local arb-prec oracle set; algebraic self-checks
// (`erf(z*) = conj(erf(z))`, `erf + erfc = 1`, parity) supplement.
//
// Probed against: WolframScript 1.13.0, Mathematica kernel 14.3.0 for Linux
// x86 (64-bit), released 2025-07-08. Re-runs on a different kernel version
// will record that version in the `oracle_kernel_version` field of every
// output record; downstream comparators should treat results carrying a
// different kernel version as a separate oracle generation.
//
// -----------------------------------------------------------------------------
// The Wolfram input-trap landmine (R5 §3.1 — load-bearing)
// -----------------------------------------------------------------------------
//
// The most subtle bug an oracle adapter for Wolfram can ship with: the literal
// `N[Erf[1.23], 50]` silently returns *only sixteen* digits of precision, not
// fifty. The reason is that `1.23` in Wolfram parses as a `MachinePrecision`
// double (float64); `N[head[machine-double-arg], 50]` propagates the input's
// machine precision through the call, and the requested 50 simply caps the
// *displayed* output. The fix, baked into every input the adapter constructs,
// is to wrap every decimal value as `Rational[num, den]`:
//
//     wrong:   N[Erf[1.23], 60]               -> 0.9180501041267614   (16 digits)
//     right:   N[Erf[Rational[123, 100]], 60] -> 0.91805010412676136789…  (60 digits)
//
// The probe to confirm the bug is fixed lives in the spot-check below: erf(1/2)
// against the known 50-digit reference, and erf(123/100) against R5's
// three-way-agreement value. If either spot-check disagrees in any of the
// first 50 digits, the trap is active and the adapter must fail loud.
//
// -----------------------------------------------------------------------------
// Erfcx: composition, not the Wolfram symbol
// -----------------------------------------------------------------------------
//
// Wolfram has an `Erfcx[z]` symbol but `N[Erfcx[complex-input], 60]` returns
// *unevaluated* — Wolfram 14.3's arbitrary-precision numeric evaluator does
// not implement scaled-complementary at arb-prec for complex arguments. The
// real-valued real-precision evaluator is similarly partial. To get a uniform,
// reliable answer the adapter computes erfcx via the algebraic identity
//
//     erfcx(z) = erfc(z) * exp(z^2)
//
// at the target precision. For the corpus's input ranges (T2 real |x| ≤ 6, T3
// real |x| ≤ 30, T5/T7 complex |z| ≤ 30) this composition is benign: erfc(x)
// for large positive x is exponentially small but the `exp(x^2)` factor
// compensates; computed at 60 working digits the result is correctly rounded
// to >50 digits across the entire corpus. (The substrate-side `bigErfcx`
// must NOT do this — see ADR-0040 §"Decision 3" — because the substrate's
// `--precision` is the user's request, not a fixed 60. For the oracle we have
// a fixed 60-digit working precision and can spare the cancellation budget.)
//
// -----------------------------------------------------------------------------
// Batch invocation (Wolfram cold-start cost is mandatory amortisation)
// -----------------------------------------------------------------------------
//
// Each invocation of `wolframscript` pays ~3 seconds of cold-start latency
// (R5 §"Adapter shape": "startup cost is ~2-4 s per `wolframscript`
// invocation — batch mode mandatory"). For 271 inputs that is 13 minutes if
// we invoke per-input; in batch mode it is sub-30-seconds. The adapter
// therefore emits a single `.wls` script holding all 271 evaluations in a
// `Do[...]` loop and invokes `wolframscript -file <tempfile>` exactly once.
//
// The script writes one record per input to stdout in a delimited
// pipe-separated format: `<id>|<status>|<re-str>|<im-str>`. The adapter
// parses these lines back. JSON-on-the-wire is avoided because Wolfram's
// `ExportString[..., "JSON"]` formats precision-annotated numbers with a
// trailing backtick suffix that breaks JSON parsers — pipe-delimited
// plain-text is the safer wire format here.
//
// -----------------------------------------------------------------------------
// Subprocess plumbing — mirroring the spawnBun resolver pattern
// -----------------------------------------------------------------------------
//
// ADR-0001 owns "where is `bun`?" via a PATH-walk + realpath + smoke-test
// resolver and a `spawnBun(args, stdin?)` promise wrapper. For consistency,
// `wolframscript` is resolved through the same shape (`resolveWolframscript`
// below) before being spawned: PATH-walk, realpath-collapse any symlinks,
// `wolframscript -version` smoke-test, cache. This keeps the subprocess
// idiom identical across the workbench even when the child binary is not
// `bun`.

import { spawn, spawnSync } from "node:child_process";
import { realpathSync, existsSync, writeFileSync, mkdtempSync, rmSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { delimiter, join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// -----------------------------------------------------------------------------
// Corpus + result shapes (mirroring the corpus schema)
// -----------------------------------------------------------------------------

interface CorpusInput {
  readonly id: string;
  readonly tier: string;
  readonly head: string;
  readonly z: string | { re: string; im: string };
  readonly notes?: string;
}

interface Corpus {
  readonly manifest_version: number;
  readonly inputs: ReadonlyArray<CorpusInput>;
}

interface ResultRecord {
  input_id: string;
  head: string;
  z: string | { re: string; im: string };
  output: string | { re: string; im: string };
  method: "wolfram-N-at-60-decimal";
  achieved_precision: 60;
  oracle_id: "wolfram";
  oracle_version: string;
  oracle_kernel_version: string;
  elapsed_ms: number;
  refusal?: { class: string; reason: string };
}

// -----------------------------------------------------------------------------
// Decimal-string → exact rational (BigInt num, BigInt den)
// -----------------------------------------------------------------------------
//
// The corpus stores every numeric value as a fixed-format decimal string with
// 60 digits past the decimal point — produced by JS Number.toFixed(60) — with
// two exceptions: `Number.MAX_VALUE` overflows toFixed into exponent form
// (`"1.7976931348623157e+308"`), and the symbolic literals `"NaN"`,
// `"Infinity"`, `"-Infinity"` are emitted verbatim.
//
// This function parses the finite-decimal forms into an exact BigInt rational
// `(num, den)` so it can be passed to Wolfram as `Rational[num, den]`, dodging
// the input-trap (`1.23` parsed as MachinePrecision). The symbolic literals
// are handled at the call site, not here.

type ExactRational = { num: bigint; den: bigint };

function parseDecimalToRational(s: string): ExactRational {
  if (!/^-?(\d+(\.\d*)?|\.\d+)(e[+-]?\d+)?$/i.test(s)) {
    throw new Error(
      `parseDecimalToRational: malformed decimal '${s}'. ` +
      `suggestion: the corpus is supposed to emit toFixed(60) or scientific notation; ` +
      `if this string came from the corpus a regeneration bug has occurred.`
    );
  }
  // Split into sign, mantissa, exponent.
  let sign = 1n;
  let rest = s;
  if (rest.startsWith("-")) {
    sign = -1n;
    rest = rest.slice(1);
  } else if (rest.startsWith("+")) {
    rest = rest.slice(1);
  }
  let exp = 0;
  const eIdx = rest.search(/[eE]/);
  if (eIdx >= 0) {
    exp = Number.parseInt(rest.slice(eIdx + 1), 10);
    rest = rest.slice(0, eIdx);
  }
  const dot = rest.indexOf(".");
  let intPart: string;
  let fracPart: string;
  if (dot < 0) {
    intPart = rest;
    fracPart = "";
  } else {
    intPart = rest.slice(0, dot);
    fracPart = rest.slice(dot + 1);
  }
  // Strip leading zeros from intPart for readability (preserving "0" if empty).
  if (intPart === "") intPart = "0";
  // Numerator before sign/exp = intPart * 10^fracPart.length + fracPart (as int).
  // Denominator base = 10^fracPart.length.
  let numStr = intPart + fracPart;
  // Trim leading zeros to avoid bigint surprises.
  numStr = numStr.replace(/^0+(?=\d)/, "");
  let num = numStr === "" ? 0n : BigInt(numStr);
  let denExp = fracPart.length - exp; // effective denominator exponent
  let den: bigint;
  if (denExp >= 0) {
    den = 10n ** BigInt(denExp);
  } else {
    // Negative denominator exponent: multiply numerator instead.
    num = num * 10n ** BigInt(-denExp);
    den = 1n;
  }
  num = sign * num;
  // Reduce by GCD for cleanliness.
  const g = gcd(num < 0n ? -num : num, den);
  return { num: num / g, den: den / g };
}

function gcd(a: bigint, b: bigint): bigint {
  while (b !== 0n) {
    [a, b] = [b, a % b];
  }
  return a;
}

// -----------------------------------------------------------------------------
// Per-input Wolfram code emission
// -----------------------------------------------------------------------------
//
// Given a corpus input record, build the WL fragment that evaluates that
// input's named head at precision 60 and prints one classification line. The
// canonical forms (Wolfram symbol names) are:
//
//   "Erf"           -> Erf[z]
//   "Erfc"          -> Erfc[z]
//   "Erfcx"         -> Erfc[z] * Exp[z^2]      (composition; Wolfram's Erfcx is partial at N[])
//   "Erfi"          -> Erfi[z]
//   "InverseErf"    -> InverseErf[z]
//   "InverseErfc"   -> InverseErfc[z]

const KNOWN_HEADS = new Set([
  "Erf", "Erfc", "Erfcx", "Erfi", "InverseErf", "InverseErfc",
]);

/** Produce the Wolfram-side expression body for `head[zExpr]`. */
function wlBodyFor(head: string, zExpr: string): string {
  switch (head) {
    case "Erf": return `Erf[${zExpr}]`;
    case "Erfc": return `Erfc[${zExpr}]`;
    case "Erfcx": {
      // Always compute as Erfc[z] * Exp[z^2] at the target precision so the
      // composition is reliable for complex z too (see top-of-file commentary).
      return `Erfc[${zExpr}] * Exp[(${zExpr})^2]`;
    }
    case "Erfi": return `Erfi[${zExpr}]`;
    case "InverseErf": return `InverseErf[${zExpr}]`;
    case "InverseErfc": return `InverseErfc[${zExpr}]`;
    default: throw new Error(`wlBodyFor: unknown head '${head}'`);
  }
}

/** Convert a corpus-z (string or {re,im}) into a Wolfram z-expression. */
function corpusZToWlExpr(z: string | { re: string; im: string }): string {
  if (typeof z === "string") return decimalStringToWl(z);
  // Complex: re + im * I, each as exact Rational unless symbolic.
  const re = decimalStringToWl(z.re);
  const im = decimalStringToWl(z.im);
  // Avoid `(re) + (Indeterminate)*I` — if either side is Indeterminate the
  // whole expression is Indeterminate by Wolfram's algebra; for Infinity the
  // sum is DirectedInfinity (ComplexInfinity-ish), which classifier handles.
  return `(${re}) + (${im}) * I`;
}

function decimalStringToWl(s: string): string {
  if (s === "NaN") return "Indeterminate";
  if (s === "Infinity") return "Infinity";
  if (s === "-Infinity") return "-Infinity";
  const r = parseDecimalToRational(s);
  if (r.den === 1n) return r.num.toString(); // exact integer
  return `Rational[${r.num.toString()}, ${r.den.toString()}]`;
}

// -----------------------------------------------------------------------------
// Build the batch .wls program
// -----------------------------------------------------------------------------

const BATCH_PREAMBLE = `
(* Generated by bench/erf-anchor/oracles/wolfram/adapter.ts. *)

(* Disable Wolfram's default Print line-wrapping. A bare default of           *)
(* $PageWidth ~ 78 chops 60-decimal outputs across multiple physical lines    *)
(* and breaks the consumer's record parser. Infinity = no wrapping ever.     *)
$PageWidth = Infinity;

(* The classifier dispatches on the numeric-evaluation result so unevaluated *)
(* symbolic forms (e.g. InverseErf[2] for out-of-domain input) refuse cleanly*)
(* rather than echoing a non-number as if it were one.                       *)
ClassifyResult[r_] := Which[
  r === Indeterminate, "INDETERMINATE",
  r === Infinity, "POS-INFINITY",
  r === -Infinity, "NEG-INFINITY",
  r === ComplexInfinity || Head[r] === DirectedInfinity, "COMPLEX-INFINITY",
  IntegerQ[r] || Head[r] === Rational, "EXACT-NUMERIC",
  InexactNumberQ[r], "INEXACT-NUMERIC",
  True, "REFUSE"
];

(* PrintRecord emits one line per input. The separator is "|"; the consumer *)
(* TS adapter splits on "|" and never expects "|" inside a numeric token.   *)
(*                                                                          *)
(* Underflow[]/Overflow[] handling: for inputs whose magnitude pushes Erf   *)
(* / Erfc / Erfi past the kernel's $MaxExtraPrecision floor, Wolfram emits  *)
(* a wrapper symbol like '1 - Underflow[]' instead of evaluating to the     *)
(* limit. We replace Underflow[] -> 0 and Overflow[] -> Infinity and re-    *)
(* evaluate; this collapses the result to the structural limit (e.g.       *)
(* '1 - Underflow[]' -> '1'). For the Erfcx composition (Erfc[z] Exp[z^2]) *)
(* at huge x, this produces 0*Infinity = Indeterminate, which the           *)
(* classifier returns as INDETERMINATE — an honest refusal: the gold       *)
(* oracle does not produce a value for this input via this composition.    *)
PrintRecord[id_, expr_] := Module[{r, replaced, cls, reStr, imStr},
  r = Quiet[N[expr, 60]];
  replaced = r /. {Underflow[] -> 0, Overflow[] -> Infinity};
  replaced = Quiet[N[replaced, 60]];
  cls = ClassifyResult[replaced];
  Which[
    cls === "INEXACT-NUMERIC",
      reStr = ToString[Re[replaced], InputForm];
      imStr = ToString[Im[replaced], InputForm];
      Print[StringJoin[id, "|INEXACT|", reStr, "|", imStr]],
    cls === "EXACT-NUMERIC",
      Print[StringJoin[id, "|EXACT|", ToString[replaced, InputForm], "|0"]],
    True,
      Print[StringJoin[id, "|", cls, "||"]]
  ]
];

(* Header for the consumer: capture versions before any numerical work, so *)
(* even if every evaluation aborts the version probe still succeeds.       *)
Print[StringJoin["__VERSIONS__|", ToString[$VersionNumber], "|", $Version]];
`.trim() + "\n";

function buildBatchProgram(inputs: ReadonlyArray<CorpusInput>): string {
  const lines: string[] = [BATCH_PREAMBLE];
  for (const inp of inputs) {
    if (!KNOWN_HEADS.has(inp.head)) {
      throw new Error(
        `buildBatchProgram: corpus input ${inp.id} has unknown head '${inp.head}'. ` +
        `suggestion: extend KNOWN_HEADS / wlBodyFor in adapter.ts to support it.`
      );
    }
    const zExpr = corpusZToWlExpr(inp.z);
    const body = wlBodyFor(inp.head, zExpr);
    // Use String literal id — assume ids contain only [A-Za-z0-9-] which is
    // safe inside a Wolfram String[].
    lines.push(`PrintRecord["${inp.id}", ${body}];`);
  }
  return lines.join("\n");
}

// -----------------------------------------------------------------------------
// wolframscript output parser — strip precision suffixes and normalize forms
// -----------------------------------------------------------------------------
//
// A Wolfram InputForm decimal carries a precision annotation appended after a
// backtick: `0.918050…`60.` (real) or `0.…`59.96099923118899` (complex with
// per-component tracked precision). The annotation is informative for the
// kernel; the consumer wants only the decimal-string body. The regex strips
// from the first backtick to end-of-string.
//
// One subtlety: Wolfram's InputForm of a non-trivial decimal sometimes has a
// trailing dot before the backtick (`-1.\`60.`). The dot is informational
// (it asserts "this is a real number" rather than an integer); we preserve
// the leading sign and digits up to but not including the backtick, then drop
// any trailing dot. Result: `-1` or `-1.234`.

function stripPrecisionSuffix(s: string): string {
  const tick = s.indexOf("`");
  let body = tick >= 0 ? s.slice(0, tick) : s;
  // Trailing dot: "1." becomes "1"; "1.0" stays "1.0".
  if (body.endsWith(".")) body = body.slice(0, -1);
  return body;
}

interface ParsedRecord {
  id: string;
  status: "INEXACT" | "EXACT" | "INDETERMINATE" | "POS-INFINITY" | "NEG-INFINITY" | "COMPLEX-INFINITY" | "REFUSE";
  re: string;
  im: string;
}

function parseBatchStdout(stdout: string): { versions: { number: string; long: string }; records: ParsedRecord[] } {
  const records: ParsedRecord[] = [];
  let versions: { number: string; long: string } | null = null;
  for (const rawLine of stdout.split("\n")) {
    const line = rawLine.replace(/\r$/, "");
    if (line === "") continue;
    if (line.startsWith("__VERSIONS__|")) {
      const parts = line.split("|");
      if (parts.length < 3) {
        throw new Error(`parseBatchStdout: malformed __VERSIONS__ line: ${line}`);
      }
      versions = { number: parts[1] ?? "", long: parts.slice(2).join("|") };
      continue;
    }
    const parts = line.split("|");
    if (parts.length < 4) {
      // Wolfram diagnostics (`General::stop`, `Erfc::indet`) print without our
      // delimiter shape. Surface them on stderr but do not abort — the per-
      // input classifier still produces a refusal record for genuinely-bad
      // inputs. Lines that look like Wolfram messages are silently filtered.
      if (/::/.test(line)) {
        process.stderr.write(`[wolfram-msg] ${line}\n`);
        continue;
      }
      throw new Error(`parseBatchStdout: malformed record line: '${line}'`);
    }
    const [id, status, re, im] = parts as [string, ParsedRecord["status"], string, string];
    const valid = new Set(["INEXACT", "EXACT", "INDETERMINATE", "POS-INFINITY", "NEG-INFINITY", "COMPLEX-INFINITY", "REFUSE"]);
    if (!valid.has(status)) {
      throw new Error(`parseBatchStdout: unknown status '${status}' in line '${line}'`);
    }
    // Some complex outputs (Erfcx via composition) may contain the "*I" tail
    // in the re/im fragments because Re[]/Im[] applied to a sum can produce
    // longer subexpressions. For our classifier path that's only on the
    // INEXACT branch and Re[]/Im[] of an InexactNumber gives only digits.
    records.push({ id, status, re: re ?? "", im: im ?? "" });
  }
  if (versions === null) {
    throw new Error(
      `parseBatchStdout: did not find __VERSIONS__ line in wolframscript stdout. ` +
      `suggestion: wolframscript may have failed before reaching the version probe; ` +
      `check stderr for an early-abort diagnostic.`
    );
  }
  return { versions, records };
}

// -----------------------------------------------------------------------------
// Wolframscript resolver — mirrors the spawnBun resolver shape
// -----------------------------------------------------------------------------

let cachedWolframscript: string | null = null;

function resolveWolframscript(): string {
  if (cachedWolframscript !== null) return cachedWolframscript;
  const fromEnv = process.env["WOLFRAMSCRIPT_BIN"];
  let initial: string | null = fromEnv && fromEnv.length > 0 ? fromEnv : null;
  if (initial === null) {
    const path = process.env["PATH"] ?? "";
    for (const dir of path.split(delimiter)) {
      if (!dir) continue;
      const candidate = join(dir, "wolframscript");
      if (existsSync(candidate)) { initial = candidate; break; }
    }
  }
  if (initial === null) {
    throw new Error(
      `resolveWolframscript: cannot find 'wolframscript' on PATH and ` +
      `WOLFRAMSCRIPT_BIN is unset. ` +
      `suggestion: install Wolfram Mathematica or set WOLFRAMSCRIPT_BIN to ` +
      `the absolute path.`
    );
  }
  let real: string;
  try { real = realpathSync(initial); }
  catch (e) {
    throw new Error(`resolveWolframscript: '${initial}' does not resolve via realpath: ${(e as Error).message}`);
  }
  const probe = spawnSync(real, ["-version"], { stdio: ["ignore", "pipe", "pipe"] });
  if (probe.error || probe.status !== 0) {
    const detail = probe.error ? probe.error.message :
      `exit ${probe.status}: ${probe.stderr?.toString().trim() ?? ""}`;
    throw new Error(
      `resolveWolframscript: resolved to '${real}' but cannot invoke it ` +
      `(${detail}). suggestion: confirm the Wolfram kernel is activated ` +
      `(wolframscript -code 'Print[1+1]').`
    );
  }
  cachedWolframscript = real;
  return real;
}

interface SpawnResult { code: number; stdout: string; stderr: string; }

function runWolframscriptFile(scriptPath: string): Promise<SpawnResult> {
  const bin = resolveWolframscript();
  return new Promise((resolve, reject) => {
    const p = spawn(bin, ["-file", scriptPath], { stdio: ["ignore", "pipe", "pipe"] });
    let stdout = "";
    let stderr = "";
    p.stdout?.on("data", (b) => (stdout += (b as Buffer).toString("utf8")));
    p.stderr?.on("data", (b) => (stderr += (b as Buffer).toString("utf8")));
    p.on("error", reject);
    p.on("close", (code) => resolve({ code: code ?? 0, stdout, stderr }));
  });
}

function probeWolframscriptCliVersion(): string {
  const bin = resolveWolframscript();
  const probe = spawnSync(bin, ["-version"], { stdio: ["ignore", "pipe", "pipe"] });
  if (probe.error || probe.status !== 0) {
    throw new Error(`probeWolframscriptCliVersion: ${probe.error?.message ?? probe.stderr?.toString()}`);
  }
  return probe.stdout.toString().trim();
}

// -----------------------------------------------------------------------------
// Status → result-record conversion
// -----------------------------------------------------------------------------

function buildResultRecord(
  inp: CorpusInput,
  parsed: ParsedRecord,
  oracleVersion: string,
  oracleKernelVersion: string,
  elapsedMs: number,
): ResultRecord {
  const base: Omit<ResultRecord, "output" | "refusal"> = {
    input_id: inp.id,
    head: inp.head,
    z: inp.z,
    method: "wolfram-N-at-60-decimal",
    achieved_precision: 60,
    oracle_id: "wolfram",
    oracle_version: oracleVersion,
    oracle_kernel_version: oracleKernelVersion,
    elapsed_ms: elapsedMs,
  };

  switch (parsed.status) {
    case "INEXACT": {
      const re = stripPrecisionSuffix(parsed.re);
      const im = stripPrecisionSuffix(parsed.im);
      const isComplexInput = typeof inp.z !== "string";
      const imIsZero = im === "0" || /^-?0(\.0+)?$/.test(im);
      // If the *input* was real (z is a string) we emit a scalar string;
      // otherwise we emit {re, im} even if im happens to be the literal "0"
      // so downstream comparators preserve shape.
      if (!isComplexInput && imIsZero) {
        return { ...base, output: re };
      }
      return { ...base, output: { re, im } };
    }
    case "EXACT": {
      // Exact integers / rationals are returned as-is. Erfc[Infinity] = 0,
      // Erfc[-Infinity] = 2, etc. Preserve as a scalar string for real inputs.
      const v = parsed.re;
      const isComplexInput = typeof inp.z !== "string";
      if (!isComplexInput) return { ...base, output: v };
      return { ...base, output: { re: v, im: "0" } };
    }
    case "INDETERMINATE":
      return { ...base, output: "Indeterminate" };
    case "POS-INFINITY":
      return { ...base, output: "Infinity" };
    case "NEG-INFINITY":
      return { ...base, output: "-Infinity" };
    case "COMPLEX-INFINITY":
      return { ...base, output: "ComplexInfinity" };
    case "REFUSE":
      // Symbolic-unevaluated outputs (e.g. InverseErf[2] for an out-of-domain
      // input). Honest refusal: this oracle declines to provide a numeric
      // answer because Wolfram itself declines. The downstream comparator
      // treats a refusal record as "no oracle value here", not "wrong oracle
      // value".
      return {
        ...base,
        output: "Indeterminate",
        refusal: {
          class: "wolfram/symbolic-unevaluated",
          reason: `Wolfram's N[${inp.head}[z], 60] returned an unevaluated symbolic form; ` +
                  `the head is not defined numerically for this argument (out-of-domain or no closed-form).`,
        },
      };
  }
}

// -----------------------------------------------------------------------------
// Main entry
// -----------------------------------------------------------------------------

async function main(): Promise<void> {
  const here = dirname(fileURLToPath(import.meta.url));
  const corpusPath = join(here, "..", "..", "corpus.json");
  const outputPath = join(here, "results.json");

  // 1. Load corpus.
  const corpusRaw = readFileSync(corpusPath, "utf8");
  const corpus: Corpus = JSON.parse(corpusRaw);
  if (!Array.isArray(corpus.inputs) || corpus.inputs.length === 0) {
    throw new Error(
      `adapter: corpus at ${corpusPath} has no inputs (or is malformed). ` +
      `suggestion: regenerate via 'bun bench/erf-anchor/generate-corpus.ts'.`
    );
  }

  // 2. Probe wolframscript CLI version up-front (so we record it even if
  // the batch program itself aborts).
  const cliVersion = probeWolframscriptCliVersion();
  process.stderr.write(`[wolfram-adapter] CLI: ${cliVersion}\n`);
  process.stderr.write(`[wolfram-adapter] inputs in corpus: ${corpus.inputs.length}\n`);

  // 3. Build the batch program and write to a tempfile.
  const program = buildBatchProgram(corpus.inputs);
  const td = mkdtempSync(join(tmpdir(), "wolfram-erf-oracle-"));
  const scriptPath = join(td, "batch.wls");
  writeFileSync(scriptPath, program, "utf8");

  // 4. Execute. Time the whole batch.
  const t0 = Date.now();
  let runResult: SpawnResult;
  try {
    runResult = await runWolframscriptFile(scriptPath);
  } finally {
    // Tempfile is small; clean up to leave the system tidy.
    try { rmSync(td, { recursive: true, force: true }); } catch { /* ignore */ }
  }
  const totalElapsed = Date.now() - t0;

  if (runResult.code !== 0) {
    throw new Error(
      `adapter: wolframscript exited with code ${runResult.code}.\n` +
      `stderr (tail):\n${runResult.stderr.slice(-1000)}\n` +
      `suggestion: re-run with WOLFRAMSCRIPT_BIN set to the kernel-script binary, ` +
      `or run the program directly via 'wolframscript -file <scriptPath>' for diagnostics.`
    );
  }

  // 5. Parse.
  const { versions, records } = parseBatchStdout(runResult.stdout);
  process.stderr.write(`[wolfram-adapter] kernel: ${versions.long}\n`);
  process.stderr.write(`[wolfram-adapter] parsed ${records.length} records in ${totalElapsed} ms\n`);

  if (records.length !== corpus.inputs.length) {
    throw new Error(
      `adapter: expected ${corpus.inputs.length} records, got ${records.length}. ` +
      `suggestion: a Wolfram per-input failure may have aborted printing; ` +
      `inspect stderr (above) for the failing input id.`
    );
  }

  // 6. Re-shape: build per-input result records, preserving corpus order.
  const recordById = new Map<string, ParsedRecord>(records.map((r) => [r.id, r]));
  const oracleCliVersion = cliVersion;
  const oracleKernelVersion = versions.long;
  // Amortise total elapsed evenly per-input as a coarse approximation; the
  // batch program does not time individual evaluations to keep the wire
  // format simple.
  const perInputElapsed = Math.round(totalElapsed / corpus.inputs.length);

  const results: ResultRecord[] = corpus.inputs.map((inp) => {
    const parsed = recordById.get(inp.id);
    if (parsed === undefined) {
      throw new Error(
        `adapter: corpus input ${inp.id} missing from wolframscript output. ` +
        `suggestion: a per-input Wolfram diagnostic may have prevented PrintRecord from running; ` +
        `re-execute with diagnostics on for that id.`
      );
    }
    return buildResultRecord(inp, parsed, oracleCliVersion, oracleKernelVersion, perInputElapsed);
  });

  // 7. Wrap into the file-level envelope.
  const envelope = {
    manifest_version: 1,
    generated_at: new Date().toISOString(),
    bead: "scientist-workbench-ufgd",
    adr: "0040",
    oracle_id: "wolfram",
    oracle_tier: "gold",
    oracle_version: oracleCliVersion,
    oracle_kernel_version: oracleKernelVersion,
    method: "wolfram-N-at-60-decimal",
    achieved_precision: 60,
    notes: [
      "Erfcx is computed as Erfc[z] * Exp[z^2] (Wolfram 14.3's Erfcx N[] is partial).",
      "Decimal inputs are always wrapped as Rational[num,den] to dodge the MachinePrecision input-trap (R5 §3.1).",
      "Refusal records (refusal.class = 'wolfram/symbolic-unevaluated') mark inputs Wolfram declined to evaluate numerically.",
    ],
    total_inputs: corpus.inputs.length,
    total_elapsed_ms: totalElapsed,
    results,
  };

  writeFileSync(outputPath, JSON.stringify(envelope, null, 2) + "\n", "utf8");
  const refusals = results.filter((r) => r.refusal !== undefined).length;
  process.stdout.write(
    `Wrote N=${results.length} results (refusals=${refusals}) in ${totalElapsed}ms ` +
    `-> ${outputPath}\n`
  );
}

if (import.meta.main || import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    process.stderr.write(`[wolfram-adapter] FAIL: ${(err as Error).message}\n`);
    process.exitCode = 1;
  });
}
