// =============================================================================
// nodes-weights-bf.ts — G7K15 nodes and weights at arbitrary precision
// =============================================================================
//
// Intent
// ------
// The arb-prec G7K15 driver (`gauss-kronrod-bf.ts`) needs the seven-point
// Gauss-Legendre + 15-point Kronrod nodes and weights as `BigFloat` values
// rounded to its working precision. This file is the single source of truth
// for those constants, and the only home in the package where 200-decimal-
// digit literals live.
//
// We *cannot* derive these from the float64 GSL constants in `gauss-kronrod.ts`
// — those carry only ~16 trustworthy digits, and naively converting via
// `fromFloat64` would re-introduce float64-precision rounding into a substrate
// we are deliberately keeping above it. The arb-prec values are stored as
// 200-dps decimal string literals and parsed lazily into the requested
// working precision via `fromString`.
//
// Generation oracle (the cited regeneration recipe — Law 1 & 2)
// -------------------------------------------------------------
// All constants below were generated by the script transcribed in this
// header comment. Rerunning the script at `mp.dps = 230` reproduces the
// values byte-for-byte (the 200-dps strings are the leading-200-digit
// truncation of mpmath's 230-dps output; the 30-digit safety margin is
// absorbed by mpmath's internal rounding). Saved as a comment, not a
// committed `.py` file, because the regeneration is rare and auditing
// the recipe in-place beats hunting for a sibling script.
//
// ```python
// from mpmath import mp, mpf, polyroots, lu_solve, matrix, quad
// mp.dps = 230
//
// # Gauss-Legendre 7-point nodes via P_7 root-finding (substitute u=x^2):
// u_roots = sorted(polyroots([mpf(429), mpf(-693), mpf(315), mpf(-35)]))
// gauss_pos_asc = [mp.sqrt(u) for u in u_roots]
//
// # Stieltjes polynomial E_8 via orthogonality to P_7(x) x^k for k=0..7
// # (k even → integrand odd → trivially zero; k odd → 4 non-trivial
// # equations for 4 even coefficients of E_8). Solve linear system.
// def P7(x): return (mpf(429)*x**7 - mpf(693)*x**5 + mpf(315)*x**3 - mpf(35)*x) / 16
// M = [[quad(lambda x, j=j, k=k: P7(x) * x**(2*j + 1 + 2*k), [-1, 1])
//       for k in range(5)] for j in range(4)]
// A = matrix([[M[j][k] for k in range(4)] for j in range(4)])
// b = matrix([-M[j][4] for j in range(4)])
// c0, c2, c4, c6 = lu_solve(A, b)
// u_kron = sorted(polyroots([mpf(1), c6, c4, c2, c0]))
// kron_pos = [mp.sqrt(u) for u in u_kron]
//
// # K15 abscissae sorted by descending |x| (GSL convention; centre last):
// xgk_by_index = sorted(gauss_pos_asc + kron_pos, reverse=True) + [mpf(0)]
//
// # K15 weights via Vandermonde-on-x^{2k} for k=0..7 (8 equations,
// # 8 unknowns: 7 paired weights + 1 centre weight):
// A_w = matrix(8, 8); b_w = matrix(8, 1)
// for k in range(8):
//     for i in range(7):
//         A_w[k, i] = 2 * xgk_by_index[i]**(2*k)
//     A_w[k, 7] = mpf(1) if k == 0 else mpf(0)
//     b_w[k, 0] = mpf(2) / mpf(2*k + 1)
// w_kron = lu_solve(A_w, b_w)
//
// # G7 weights at the Gauss-shared and centre positions:
// def dP7(x): return (mpf(7*429)*x**6 - mpf(5*693)*x**4 + mpf(3*315)*x**2 - mpf(35)) / 16
// wg_centre = mpf(2) / dP7(mpf(0))**2
// wg_desc = list(reversed([mpf(2) / ((1 - x**2) * dP7(x)**2) for x in gauss_pos_asc]))
//
// # Cancellation-stable difference weights (WGK[i] - WG_i) at Gauss positions:
// dwgk_gauss = [w_kron[1, 0] - wg_desc[0],   # XGK[1] is the largest Gauss node
//               w_kron[3, 0] - wg_desc[1],   # XGK[3] mid Gauss
//               w_kron[5, 0] - wg_desc[2]]   # XGK[5] smallest Gauss (positive)
// dwgk_centre = w_kron[7, 0] - wg_centre
// ```
//
// Cross-validation (Law 1)
// ------------------------
// 1. **Truncating to float64 reproduces GSL `qk15.c` byte-for-byte** at all
//    16 entries (XGK[0..7], WGK[0..7], WG[0..3]). Verified during the
//    initial generation: `|truncated_arbprec_value - GSL_float64_value|
//    = 0.0` at all positions. GSL's source comment states the constants
//    were "evaluated with 80 decimal digit arithmetic by L. W. Fullerton,
//    Bell Labs, Nov. 1981" — well above float64; our 200-dps regeneration
//    matches Fullerton's truncation exactly.
// 2. **Algebraic exactness on x^{2k}, k=0..11** (degrees 0..22; K15 is
//    exact through degree 23): the Vandermonde-residual under our
//    constants is at the mpmath-floor (~1e-231 at 230 dps) for every
//    such k, and a non-trivial 5.7e-9 at degree 24 (k=12), confirming
//    the 23-degree exactness boundary.
//
// Cap (Law 8 — honest scope)
// --------------------------
// Maximum supported decimal precision is `MAX_DECIMAL_PRECISION = 150`. The
// 200-dps storage gives a 50-dps safety margin; after `decimalToBinaryPrecision
// (150, safety=30)` the working precision is ~530 bits, comfortably below
// the table's ~665-bit storage. A user requesting `prec > 150` gets a
// loud `RangeError`. ADR-0021 records the rationale; if a workload demands
// it, extend the table (or compute via Golub-Welsch on the Jacobi matrix
// at runtime) — do not silently degrade.

import {
  type BigFloat,
  fromString,
  decimalToBinaryPrecision,
} from "@workbench/bigfloat";

// -----------------------------------------------------------------------------
// 200-dps decimal string constants
// -----------------------------------------------------------------------------
//
// Index conventions match GSL `qk15.c`:
//   * `XGK[0..6]` are the seven *positive* Kronrod abscissae, in
//     decreasing magnitude order.
//   * `XGK[7] = 0` is the centre.
//   * The negative reflections of `XGK[0..6]` are also Kronrod abscissae
//     by symmetry of K15.
//   * `XGK[1], XGK[3], XGK[5]` are the (positive) Gauss-Legendre 7-point
//     nodes — they double as Kronrod nodes via the rule's nesting.
//     `XGK[0], XGK[2], XGK[4], XGK[6]` are Kronrod-only.
//
//   * `WGK[i]` is the Kronrod weight at `±XGK[i]` (or just `XGK[7]` for
//     the centre). The local rule's K15 estimate is
//         halfLength · ( WGK[7] · f(centre)
//                        + Σ_{i=0..6} WGK[i] · (f(c-h·XGK[i]) + f(c+h·XGK[i])) ).
//
//   * `WG[0..2]` are the G7 weights at `±XGK[1]`, `±XGK[3]`, `±XGK[5]`
//     respectively; `WG[3]` is the G7 centre weight.
//
//   * `WGK_MINUS_WG[0..2]` are the precomputed differences
//     `WGK[1]-WG[0]`, `WGK[3]-WG[1]`, `WGK[5]-WG[2]` — used by the
//     cancellation-stable error estimator (see `gauss-kronrod-bf.ts`).
//   * `WGK_MINUS_WG_CENTRE` is `WGK[7] - WG[3]`.

const XGK_DPS200: readonly string[] = [
  "0.99145537112081263920685469752632851664204433837033470129108741357244173934653407235924503509626841760744349505339307962867087422598329394045923173976036473676334978132815480512205029279060010449823441",
  "0.94910791234275852452618968404785126240077093767061778354876910391306333035484014080573077002792572414430073966699521619419562581135355311827778991585981008501390100017988824773230504010481514885111290",
  "0.86486442335976907278971278864092620121097230707408814860145771276706770813259572103585847859604590541475281326027861917057564279908620304707706683966782498707395790348224146972714170918147844188748345",
  "0.74153118559939443986386477328078840707414764714139026011995535196742987467218051379282683236686324705969251809311201424360005439822983534717038571527404983329607476079761071506987690269328445619581512",
  "0.58608723546769113029414483825872959843678075060436095130499289319880373607444407464511674498935942098956811555121368226547689775574791815408578190795382830158552972257717196673106952173272266100031625",
  "0.40584515137739716690660641207696146334738201409937012638704325179466381322612565532831268972774658776528675866604801867801423897740878996024582934594311524037058648501360281929467986469974941888691698",
  "0.20778495500789846760068940377324491347978440714517064971384573461986693844943520226910343227183698530560857645062737614454179259858088931415868783469656192231705241798920470852816390441442117105103367",
  "0",
];

const WGK_DPS200: readonly string[] = [
  "0.022935322010529224963732008058969591993560811275746992267507430254711815787976075946156368168156289483493617134063245239435007070892118937673882663472234540866386532911910205080714438949010420202034090",
  "0.063092092629978553290700663189204286665071157211550707113605545146983997477964874928199170264504441995865872491871943275761156794856977199036708894143531395855978112704845696492620552379943284740847174",
  "0.10479001032225018383987632254151801744375665421383061189339065133963746321576289524167571627509311333949422518201491585025167785472400230494690173623743388104574778616883044597665071348170463613098928",
  "0.14065325971552591874518959051023792039988975724799857556174546893312708093090950408097379122415555910759700350860142862035719023127330726880922167575921857605249187559833158833261047873133800327151116",
  "0.16900472663926790282658342659855028410624490030294424149734006755695680921619029112936702403855359908156070095656536556861739307964259978602029501360898451688006256774623159244435822044789186117607335",
  "0.19035057806478540991325640242101368282607807545535835588544088036744058072410212679605964605106377593834568683551138642464713542807901168980665006652396682258233320059814648026757370590740136073631969",
  "0.20443294007529889241416199923464908471651760418071835742447095312045467698546598879348374292009347554167803659293064115331863729112034098476806935675352668756595840170532759363951294602341814407737901",
  "0.20948214108472782801299917489171426369776208022370431671299800656137515132325648616816908211675949102392971459688214773522360449882328365787654118700220715830208304513275279553191788815858457932969249",
];

const WG_DPS200: readonly string[] = [
  "0.12948496616886969327061143267908201832858740225994666397720863872465523497204230871562541816292084508948440200163442788106534489381890446264963470799926103785402411631291758893693897373663251738708536",
  "0.27970539148927666790146777142377958248692506522659876453701403269361881043056267681324094290119761876632337521337205151913563697956311994437135265781233685455635920253369091926431948335024933482679093",
  "0.38183005050511894495036977548897513387836508353386273475108345103070554643412970834868465934404480145031467176458535733449289567763838375624431875663738169942635137503094251220690480821924059676571555",
  "0.41795918367346938775510204081632653061224489795918367346938775510204081632653061224489795918367346938775510204081632653061224489795918367346938775510204081632653061224489795918367346938775510204081633",
];

// Precomputed cancellation-stable weight differences (WGK − WG).
// Negative — these are subtracted from the Gauss subset's weight contribution
// to give the K15 weight, so as differences they are negative-valued.
//
// WGK_MINUS_WG_DPS200[k] is paired with the Gauss node at XGK[2k+1]:
//   k=0 → XGK[1] (largest |x| Gauss node), pair WG[0]
//   k=1 → XGK[3] (mid-magnitude Gauss),   pair WG[1]
//   k=2 → XGK[5] (smallest positive Gauss), pair WG[2]
const WGK_MINUS_WG_DPS200: readonly string[] = [
  "-0.066392873538891139979910769489877731663516245048395956863603093577671237494077433787426247898416403093618529509762484605304188098961927263612925813855729641998046003608071892444318421356689232646238189",
  "-0.13905213177375074915627818091354166208703530797860018897526856376049172949965317273226715167704205965872637170477062289877844674828981267556213098205311827850386732693535933093170900461891133155527977",
  "-0.19147947244033353503711337306796145105228700807850437886564257066326496571002758155262501329298102551196898492907397090984576024955937206643766869011341487684401817443279603193933110231183923602939586",
];

// WGK[7] − WG[3] for the centre. Used to evaluate K-G's centre contribution
// without the catastrophic cancellation from computing WGK[7]·f and WG[3]·f
// separately and subtracting at high precision.
const WGK_MINUS_WG_CENTRE_DPS200 =
  "-0.20847704258874155974210286592461226691448281773547935675638974854066566500327412607672887706691397836382538744393417879538864039913590001559284656809983365802444756711214516365175558122917052271112384";

// -----------------------------------------------------------------------------
// Public API: cap and the lazily-cached BigFloat table
// -----------------------------------------------------------------------------

/**
 * Maximum decimal precision the arb-prec G7K15 driver supports. Beyond this,
 * the stored 200-dps constants no longer give the working precision enough
 * headroom — we refuse loudly rather than silently degrade.
 *
 * Senior-engineer rule (Law 8 — honest scope): a tool that produces a wrong-
 * shaped or wrong-valued answer past its declared scope is inadmissible, no
 * matter how cleverly it tries. The 150-dps cap is the line.
 */
export const MAX_DECIMAL_PRECISION = 150;

/**
 * The G7K15 nodes and weights, parsed at a specific working bit-precision.
 *
 * The driver requests this at its working precision (typically `prec * 3.32
 * + 30` bits for a `prec`-decimal-digit user request); the parsed table is
 * cached so successive bisections share one table.
 */
export interface G7K15Table {
  /** Bit precision the table is parsed at. */
  readonly workingBits: number;
  /** Positive Kronrod abscissae, descending magnitude; index 7 is the centre (0). */
  readonly xgk: readonly BigFloat[];
  /** Kronrod weights at `±xgk[i]` (and centre at index 7). */
  readonly wgk: readonly BigFloat[];
  /** Gauss weights: indices 0..2 at `±xgk[1]`, `±xgk[3]`, `±xgk[5]`; index 3 is centre. */
  readonly wg: readonly BigFloat[];
  /**
   * Precomputed `WGK[2k+1] − WG[k]` differences for k=0..2 — used by the
   * cancellation-stable error estimator. Negative-valued.
   */
  readonly wgkMinusWg: readonly BigFloat[];
  /** `WGK[7] − WG[3]` — centre's cancellation-stable difference. */
  readonly wgkMinusWgCentre: BigFloat;
}

const tableCache = new Map<number, G7K15Table>();

/**
 * Get the G7K15 nodes/weights table at the given working bit precision.
 *
 * First call at a given `workingBits` parses the 200-dps strings into
 * BigFloat values and caches the table; subsequent calls at the same
 * precision return the cached table directly. Cache is unbounded (one
 * entry per distinct working precision); the typical adaptive driver
 * uses one precision throughout a run, so the cache never grows past
 * a small handful of entries even across many `gaussKronrodAdaptiveBF`
 * invocations.
 *
 * Throws `RangeError` if `workingBits < 1` or if the requested precision
 * would correspond to more than `MAX_DECIMAL_PRECISION` decimal digits
 * (with the standard 30-bit safety margin removed, i.e. the user-facing
 * limit; the bit-precision boundary is a conservative restatement of
 * the decimal cap).
 */
export function getG7K15Table(workingBits: number): G7K15Table {
  if (!Number.isInteger(workingBits) || workingBits < 1) {
    throw new RangeError(
      `getG7K15Table: workingBits must be a positive integer; got ${workingBits}`,
    );
  }
  // Defensive cap: convert MAX_DECIMAL_PRECISION to bits and refuse anything
  // beyond. The driver's `prec ≤ MAX_DECIMAL_PRECISION` check happens at
  // the user surface; this is a belt-and-braces internal guard against a
  // caller routing an unexpected working precision through.
  const maxBits = decimalToBinaryPrecision(MAX_DECIMAL_PRECISION, 30);
  if (workingBits > maxBits) {
    throw new RangeError(
      `getG7K15Table: workingBits=${workingBits} exceeds the table's safe ` +
        `precision ceiling (${maxBits} bits ≈ ${MAX_DECIMAL_PRECISION} decimal digits ` +
        `with 30-bit safety). Extend the 200-dps tables in nodes-weights-bf.ts ` +
        `or compute weights at runtime via Golub-Welsch on the Jacobi matrix.`,
    );
  }

  const cached = tableCache.get(workingBits);
  if (cached !== undefined) return cached;

  const table: G7K15Table = {
    workingBits,
    xgk: XGK_DPS200.map((s) => fromString(s, workingBits)),
    wgk: WGK_DPS200.map((s) => fromString(s, workingBits)),
    wg: WG_DPS200.map((s) => fromString(s, workingBits)),
    wgkMinusWg: WGK_MINUS_WG_DPS200.map((s) => fromString(s, workingBits)),
    wgkMinusWgCentre: fromString(WGK_MINUS_WG_CENTRE_DPS200, workingBits),
  };
  tableCache.set(workingBits, table);
  return table;
}

/**
 * Clear the parsed-table cache. Test-only escape hatch; production code
 * never needs this. Exposed so a long-running orchestrator that processes
 * many distinct precisions in sequence can reclaim memory if it really
 * wants to (in practice the cache stays tiny).
 */
export function _clearG7K15TableCacheForTesting(): void {
  tableCache.clear();
}
