import { expr, int, rat, record, sym, tagged } from "@workbench/protocol";
import type { GoldenSpec } from "@workbench/contract";

export const goldens: GoldenSpec[] = [
  { description: "x = x", input: record({ lhs: sym("x"), rhs: sym("x") }) },
  { description: "0 = 0", input: record({ lhs: int(0n), rhs: int(0n) }) },
  { description: "1 + 1 = 2", input: record({ lhs: expr("+", [int(1n), int(1n)]), rhs: int(2n) }) },
  { description: "(x+1)^2 = x^2 + 2x + 1", input: record({ lhs: expr("^", [expr("+", [sym("x"), int(1n)]), int(2n)]), rhs: expr("+", [expr("^", [sym("x"), int(2n)]), expr("*", [int(2n), sym("x")]), int(1n)]) }) },
  { description: "(x+1)(x-1) = x^2 - 1", input: record({ lhs: expr("*", [expr("+", [sym("x"), int(1n)]), expr("-", [sym("x"), int(1n)])]), rhs: expr("-", [expr("^", [sym("x"), int(2n)]), int(1n)]) }) },
  { description: "(x^2 - 1)/(x - 1) = x + 1 — no GCD needed", input: record({ lhs: expr("/", [expr("-", [expr("^", [sym("x"), int(2n)]), int(1n)]), expr("-", [sym("x"), int(1n)])]), rhs: expr("+", [sym("x"), int(1n)]) }) },
  { description: "(x^3 - 1)/(x - 1) = x^2 + x + 1", input: record({ lhs: expr("/", [expr("-", [expr("^", [sym("x"), int(3n)]), int(1n)]), expr("-", [sym("x"), int(1n)])]), rhs: expr("+", [expr("^", [sym("x"), int(2n)]), sym("x"), int(1n)]) }) },
  { description: "x*y = y*x", input: record({ lhs: expr("*", [sym("x"), sym("y")]), rhs: expr("*", [sym("y"), sym("x")]) }) },
  { description: "x + y = y + x", input: record({ lhs: expr("+", [sym("x"), sym("y")]), rhs: expr("+", [sym("y"), sym("x")]) }) },
  { description: "(x+y)^2 = x^2 + 2xy + y^2", input: record({ lhs: expr("^", [expr("+", [sym("x"), sym("y")]), int(2n)]), rhs: expr("+", [expr("^", [sym("x"), int(2n)]), expr("*", [int(2n), sym("x"), sym("y")]), expr("^", [sym("y"), int(2n)])]) }) },
  { description: "(a-b)*(a+b) = a^2 - b^2", input: record({ lhs: expr("*", [expr("-", [sym("a"), sym("b")]), expr("+", [sym("a"), sym("b")])]), rhs: expr("-", [expr("^", [sym("a"), int(2n)]), expr("^", [sym("b"), int(2n)])]) }) },
  { description: "x/y * y = x", input: record({ lhs: expr("*", [expr("/", [sym("x"), sym("y")]), sym("y")]), rhs: sym("x") }) },
  { description: "1/2 + 1/3 = 5/6", input: record({ lhs: expr("+", [rat(1n, 2n), rat(1n, 3n)]), rhs: rat(5n, 6n) }) },
  { description: "1/2 * x + 1/2 * x = x", input: record({ lhs: expr("+", [expr("*", [rat(1n, 2n), sym("x")]), expr("*", [rat(1n, 2n), sym("x")])]), rhs: sym("x") }) },
  { description: "x + 1 != x + 2", input: record({ lhs: expr("+", [sym("x"), int(1n)]), rhs: expr("+", [sym("x"), int(2n)]) }) },
  { description: "x*y != y*z", input: record({ lhs: expr("*", [sym("x"), sym("y")]), rhs: expr("*", [sym("y"), sym("z")]) }) },
  { description: "(x+1)^2 != x^2 + 1 (a real algebra error)", input: record({ lhs: expr("^", [expr("+", [sym("x"), int(1n)]), int(2n)]), rhs: expr("+", [expr("^", [sym("x"), int(2n)]), int(1n)]) }) },
  { description: "x^2 / x = x", input: record({ lhs: expr("/", [expr("^", [sym("x"), int(2n)]), sym("x")]), rhs: sym("x") }) },
  { description: "(x+y)/(x+y) = 1 even without GCD", input: record({ lhs: expr("/", [expr("+", [sym("x"), sym("y")]), expr("+", [sym("x"), sym("y")])]), rhs: int(1n) }) },
  { description: "(x*y + x*z)/x = y + z", input: record({ lhs: expr("/", [expr("+", [expr("*", [sym("x"), sym("y")]), expr("*", [sym("x"), sym("z")])]), sym("x")]), rhs: expr("+", [sym("y"), sym("z")]) }) },
  { description: "negation: -x = (-1)*x", input: record({ lhs: expr("-", [sym("x")]), rhs: expr("*", [int(-1n), sym("x")]) }) },
  { description: "subtraction: a - b = a + (-1)*b", input: record({ lhs: expr("-", [sym("a"), sym("b")]), rhs: expr("+", [sym("a"), expr("*", [int(-1n), sym("b")])]) }) },
  { description: "x^3 / x = x^2", input: record({ lhs: expr("/", [expr("^", [sym("x"), int(3n)]), sym("x")]), rhs: expr("^", [sym("x"), int(2n)]) }) },
  { description: "(a+b+c)^2 = a^2 + b^2 + c^2 + 2ab + 2ac + 2bc", input: record({ lhs: expr("^", [expr("+", [sym("a"), sym("b"), sym("c")]), int(2n)]), rhs: expr("+", [expr("^", [sym("a"), int(2n)]), expr("^", [sym("b"), int(2n)]), expr("^", [sym("c"), int(2n)]), expr("*", [int(2n), sym("a"), sym("b")]), expr("*", [int(2n), sym("a"), sym("c")]), expr("*", [int(2n), sym("b"), sym("c")])]) }) },
  { description: "0 * x = 0", input: record({ lhs: expr("*", [int(0n), sym("x")]), rhs: int(0n) }) },
  { description: "x^0 = 1", input: record({ lhs: expr("^", [sym("x"), int(0n)]), rhs: int(1n) }) },
  { description: "out-of-scope: lhs has unknown head sin", input: record({ lhs: expr("sin", [sym("x")]), rhs: sym("x") }) },
  { description: "out-of-scope: rhs has unknown head", input: record({ lhs: sym("x"), rhs: expr("cos", [sym("x")]) }) },
  { description: "out-of-scope: lhs has tagged payload", input: record({ lhs: tagged("foreign", int(0n)), rhs: int(0n) }) },
  { description: "1/x + 1/y = (x+y)/(xy)", input: record({ lhs: expr("+", [expr("/", [int(1n), sym("x")]), expr("/", [int(1n), sym("y")])]), rhs: expr("/", [expr("+", [sym("x"), sym("y")]), expr("*", [sym("x"), sym("y")])]) }) },
  { description: "(a/b)/(c/d) = (a*d)/(b*c)", input: record({ lhs: expr("/", [expr("/", [sym("a"), sym("b")]), expr("/", [sym("c"), sym("d")])]), rhs: expr("/", [expr("*", [sym("a"), sym("d")]), expr("*", [sym("b"), sym("c")])]) }) },
  { description: "x^2 + 2*x + 1 = (x+1)^2 expanded as a sum", input: record({ lhs: expr("+", [expr("^", [sym("x"), int(2n)]), expr("*", [int(2n), sym("x")]), int(1n)]), rhs: expr("^", [expr("+", [sym("x"), int(1n)]), int(2n)]) }) },
  { description: "telescoping: x*(x+1) - x^2 = x", input: record({ lhs: expr("-", [expr("*", [sym("x"), expr("+", [sym("x"), int(1n)])]), expr("^", [sym("x"), int(2n)])]), rhs: sym("x") }) },
  { description: "FAIL: a^2 - b^2 != (a-b)^2 — common student error", input: record({ lhs: expr("-", [expr("^", [sym("a"), int(2n)]), expr("^", [sym("b"), int(2n)])]), rhs: expr("^", [expr("-", [sym("a"), sym("b")]), int(2n)]) }) },
];
