// =============================================================================
// bench/besselj-anchor/oracles/wolfram/adapter.ts
//   Gold-tier Wolfram Mathematica oracle adapter for the Bessel-family corpus
//   (ADR-0041 §"Decision 8" — Wolfram is the primary gold voice for J/Y/I/K).
// =============================================================================
//
// This script consumes `bench/besselj-anchor/corpus.json` (the frozen 1766-
// input manifest generated by `generate-corpus.ts`, ADR-0041 bead
// `scientist-workbench-qccc`), evaluates each input against Wolfram
// Mathematica's arbitrary-precision implementation of the Bessel family at 60
// decimal digits, and emits the canonical gold-tier golden-master file
// `bench/besselj-anchor/oracles/wolfram/results.json`.
//
// The adapter is the bench/erf-anchor sister of the Erf G2 adapter (worklog
// 138 ancestor — `bench/erf-anchor/oracles/wolfram/adapter.ts`) with three
// structural extensions for the 2-arg ν+z parameter shape and the
// modified-Bessel scaled variants:
//
//   1. INPUT-SHAPE EXTENSION. Every corpus row has both `nu` and `z` fields
//      where Erf had only `z`. The `nu` field carries three distinct kinds
//      flagged by `nu_kind ∈ {"integer", "half-integer", "decimal"}`:
//      `"integer"` is a plain int-string ("0", "-3", "50"); `"half-integer"`
//      is a fraction-string ("1/2", "-3/2", "7/2"); `"decimal"` is a
//      fixed-format JS-Number.toFixed(60) string ("1.6999…"). All three
//      kinds emit to Wolfram as exact `Rational[num, den]` (auto-reducing
//      to `Integer` when `den == 1`) so the L1 input-trap (R5 §6) is
//      defused.
//
//   2. SCALED-VARIANT COMPOSITION. The corpus admits two heads Wolfram does
//      not natively spell: `BesselIScaled := e^{-|Re z|} · I_ν(z)` and
//      `BesselKScaled := e^{z} · K_ν(z)`. These are emitted as composed
//      expressions at 60 working digits. The composition is benign in the
//      corpus's input ranges because the exponential pre-factor cancels the
//      exponentially-growing / decaying Bessel value to a moderate-magnitude
//      result (matches R5 §3.1 + the `BesselKScaled` z=700 probe yielding
//      0.0473…).
//
//   3. OUTPUT-SHAPE EXTENSION. Per the orchestrator prompt, every record
//      carries `status ∈ {"success", "limit", "refused", "error"}` and a
//      `wolfram_returned_token` field that captures the symbolic form (e.g.
//      "BesselI[0, Infinity]", "Underflow[]", "Indeterminate") when Wolfram
//      declines to produce a numeric. This is more granular than the Erf
//      adapter's `refusal: { class, reason }` shape and serves G8's
//      tier-aware tolerance-band logic directly.
//
// Probed against: WolframScript 1.13.0, Mathematica kernel 14.3.0 for Linux
// x86_64 (released 2025-07-08). Re-runs on a different kernel version will
// record that version in the `oracle_version` field of the envelope;
// downstream comparators should treat results carrying a different kernel
// version as a separate oracle generation.
//
// -----------------------------------------------------------------------------
// Wolfram input-trap (R5 §6 L1) — load-bearing
// -----------------------------------------------------------------------------
//
// The most subtle bug a Wolfram adapter can ship with: the literal
// `N[BesselJ[3, 1.23], 60]` silently returns *only sixteen* digits of
// precision, not sixty, because `1.23` parses as a `MachinePrecision` double
// (float64) and `N[…, 60]` propagates the input's machine precision through
// the call — the requested 60 caps only the *displayed* output. Same for ν:
// `N[BesselJ[0.5, Rational[3,2]], 60]` returns ~16 digits because `0.5` is a
// machine-double.
//
// The fix, baked into every input the adapter constructs: parse the corpus
// number-strings into BigInt rationals and emit them as `Rational[num, den]`
// for both ν and z. The `Rational[5,2]` form is exact; Wolfram propagates
// exactness through `BesselJ[ν, z]` to the `N[…, 60]` evaluator, which then
// computes to 60 declared digits.
//
// Reproducer (from R5 §6 L1):
//
//     wrong:   N[BesselJ[3, 2.5], 50]              -> 0.21660039103911352           (17 digits)
//     right:   N[BesselJ[3, Rational[5,2]], 50]    -> 0.216600391039113524766689…   (50 digits)
//
// Every `decimalStringToWl` call goes through `parseDecimalToRational` →
// `Rational[num, den]` (or just `num` when `den == 1` since Wolfram
// auto-reduces). The spot-checks in `parseHalfIntegerToRational` and
// `decimalStringToWl` round-trip identical decimals to exact rationals.
//
// -----------------------------------------------------------------------------
// Wolfram `*^` exponent marker (R5 §6 L_carryover) and trailing-noise
// digits (L11) — load-bearing
// -----------------------------------------------------------------------------
//
// Wolfram's `InputForm` of an arb-prec real number has the shape
// `<mantissa>BT<prec>.` (no exponent, e.g. `0.5204…BT60.`) or
// `<mantissa>BT<prec>.*^<exp>` (with the Wolfram-native `*^<exp>`
// scientific-notation marker, e.g. `6.5632…BT60.*^-343`), where BT is the
// literal backtick character. Two failures result without mitigation:
//
//   (a) The `*^` exponent marker is not standard scientific notation — any
//       cross-language JSON consumer (JS Number, Python float, awk) parses
//       it as a multiplication-with-a-typo and silently drops the exponent.
//       This is the load-bearing G2a bug from worklog 138 / bead
//       `scientist-workbench-nwdj`.
//
//   (b) The `BT<prec>.` precision-annotation suffix is invisible to every
//       downstream JSON parser. The naive "split on backtick" shaver
//       silently drops the `*^<exp>` exponent that lives *after* the
//       backtick, leaving a mantissa-only string that the comparator
//       parses as if K_0(700)≈4.67 instead of 4.67e-306.
//
// Both fixes live in the `.wls` preamble (`FormatNumeric` Wolfram function
// below): rewrite `BT<prec>.*^` → `e` first (so the exponent survives),
// then strip the trailing `BT<prec>.` suffix. The wire format is therefore
// standard-scientific (`<mantissa>e<exp>`) or plain-decimal (`<mantissa>`),
// ready for `Number()`/`parseFloat`/`Decimal` consumers.
//
// L11 — trailing-noise digits: at the emit-precision floor Wolfram emits a
// few digits of noise past the declared precision. The README documents
// this; the comparator (G8) is responsible for the tier-tolerance band.
// This adapter emits all 60 digits Wolfram produces; trimming is a
// comparator concern, not an adapter one.
//
// -----------------------------------------------------------------------------
// Underflow[]/Overflow[] post-processing (R5 §6 L9, L10)
// -----------------------------------------------------------------------------
//
// For inputs whose magnitude pushes Wolfram past `$MaxExtraPrecision`,
// Wolfram returns a wrapper symbol like `1 - Underflow[]` instead of an
// evaluated limit. The .wls batch script replaces `Underflow[] -> 0` and
// `Overflow[] -> Infinity` and re-evaluates, collapsing the structural
// limit. In practice Wolfram at 60 dps handles `K_0(700)` (≈4.67e-306) and
// `I_0(700)` (≈1.53e+302) directly — no `Underflow[]`/`Overflow[]` triggers
// — but the post-processing remains as belt-and-suspenders for any future
// corpus that pushes further (`K_0(1e6)` etc.). When the post-processing
// IS triggered, we capture Wolfram's pre-rewrite symbolic form in the
// `wolfram_returned_token` field for honesty.
//
// -----------------------------------------------------------------------------
// Limit cases — `BesselI[0, Infinity]` unevaluated (R5 §6 capability matrix)
// -----------------------------------------------------------------------------
//
// Wolfram's `N[BesselI[0, Infinity], 60]` returns the unevaluated symbolic
// form `BesselI[0, Infinity]` — even though `I_0(∞) = ∞` mathematically,
// the kernel declines to evaluate the symbol-at-symbol case. Same for
// `K_0[-Infinity]`. The adapter classifies these as `status: "limit"` (NOT
// `status: "refused"` — the function HAS a limit, Wolfram just doesn't
// volunteer it numerically) and captures the unevaluated form in
// `wolfram_returned_token`. Probed live on Wolfram 14.3 — see top-of-file
// commentary for the probe output.
//
// -----------------------------------------------------------------------------
// Batch invocation — Wolfram cold-start is ~7.6 s; per-input is ~1.4 s
// -----------------------------------------------------------------------------
//
// Each invocation of `wolframscript` pays ~7.6 seconds of cold-start latency
// (R5 §3.1). For 1766 inputs that is ~4 hours if we invoke per-input; in
// batch mode it amortises to ~1.4 s per evaluation after kernel boot, i.e.
// roughly 40-50 minutes wall-time for the full corpus. The adapter emits a
// single `.wls` script holding all 1766 evaluations in a sequential
// `PrintRecord` loop and invokes `wolframscript -file <tempfile>` exactly
// once.
//
// Why not `Do[]` / `Table[]`? Because if Wolfram's evaluation of any single
// input emits a kernel diagnostic via `Message[]`, a stop-on-error inside
// a `Table[]` would abort the rest of the loop. The flat sequence of
// per-input `PrintRecord` calls is robust to per-input diagnostics — each
// row's `Quiet[]` suppresses its messages without affecting siblings.
//
// Why not `InputString[]`-driven stdin streaming? Because Wolfram's
// `InputString[]` does NOT work in script mode (R5 explicit warning: "use
// embedded `.wls` List literal"). The corpus must be embedded inline.
//
// -----------------------------------------------------------------------------
// Subprocess plumbing — `Bun.spawn`, not `node:child_process`
// -----------------------------------------------------------------------------
//
// ADR-0001 requires `Bun.spawn` over `node:child_process`. The Erf adapter
// pre-dates this enforcement and uses `node:child_process`; this adapter
// uses `Bun.spawn` from the start. The `resolveWolframscript` helper mirrors
// the `spawnBun` resolver pattern (PATH-walk + `realpathSync` + smoke-test +
// cache) so subprocess idioms are consistent across the workbench even
// when the child binary is not `bun`.

import { realpathSync, existsSync, writeFileSync, mkdtempSync, rmSync, readFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { delimiter, join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

// -----------------------------------------------------------------------------
// Corpus + result shapes (mirroring the corpus schema)
// -----------------------------------------------------------------------------

type CorpusZ = string | { re: string; im: string };

interface CorpusInput {
  readonly id: string;
  readonly tier: string;
  readonly head: string;
  readonly nu_kind: "integer" | "half-integer" | "decimal";
  readonly nu: string;
  readonly z: CorpusZ;
  readonly z_root_index?: number;
  readonly z_root_distance?: string;
  readonly notes?: string;
}

interface Corpus {
  readonly manifest_version: number;
  readonly inputs: ReadonlyArray<CorpusInput>;
}

type ResultStatus = "success" | "refused" | "limit" | "error";

interface ResultRecord {
  input_id: string;
  status: ResultStatus;
  value: string | { re: string; im: string } | null;
  wolfram_returned_token: string | null;
  elapsed_ms: number;
  notes?: string;
}

// -----------------------------------------------------------------------------
// Decimal-string → exact rational (BigInt num, BigInt den)
// -----------------------------------------------------------------------------
//
// The corpus stores every numeric value as either:
//   (a) a fixed-format decimal string with 60 digits past the decimal point
//       (produced by JS Number.toFixed(60));
//   (b) an exponent-bearing scientific string (`"1.797…e+308"` for
//       Number.MAX_VALUE which overflows toFixed);
//   (c) symbolic literals `"NaN"`, `"Infinity"`, `"-Infinity"`;
//   (d) for half-integer ν only: a fraction string `"a/b"` like `"1/2"`,
//       `"-3/2"`, `"7/2"`.
//
// `parseDecimalToRational` handles (a) + (b); the symbolic literals (c) are
// dispatched at the call site; the fraction form (d) is handled by
// `parseFractionToRational`.

type ExactRational = { num: bigint; den: bigint };

function parseDecimalToRational(s: string): ExactRational {
  if (!/^-?(\d+(\.\d*)?|\.\d+)(e[+-]?\d+)?$/i.test(s)) {
    throw new Error(
      `parseDecimalToRational: malformed decimal '${s}'. ` +
      `suggestion: the corpus is supposed to emit toFixed(60) or scientific notation; ` +
      `if this string came from the corpus a regeneration bug has occurred.`
    );
  }
  let sign = 1n;
  let rest = s;
  if (rest.startsWith("-")) {
    sign = -1n;
    rest = rest.slice(1);
  } else if (rest.startsWith("+")) {
    rest = rest.slice(1);
  }
  let exp = 0;
  const eIdx = rest.search(/[eE]/);
  if (eIdx >= 0) {
    exp = Number.parseInt(rest.slice(eIdx + 1), 10);
    rest = rest.slice(0, eIdx);
  }
  const dot = rest.indexOf(".");
  let intPart: string;
  let fracPart: string;
  if (dot < 0) {
    intPart = rest;
    fracPart = "";
  } else {
    intPart = rest.slice(0, dot);
    fracPart = rest.slice(dot + 1);
  }
  if (intPart === "") intPart = "0";
  let numStr = intPart + fracPart;
  numStr = numStr.replace(/^0+(?=\d)/, "");
  let num = numStr === "" ? 0n : BigInt(numStr);
  const denExp = fracPart.length - exp;
  let den: bigint;
  if (denExp >= 0) {
    den = 10n ** BigInt(denExp);
  } else {
    num = num * 10n ** BigInt(-denExp);
    den = 1n;
  }
  num = sign * num;
  const g = gcd(num < 0n ? -num : num, den);
  return { num: num / g, den: den / g };
}

function parseFractionToRational(s: string): ExactRational {
  // Format: "[-]a/b" with a,b non-empty integers, b > 0. The corpus is
  // expected to emit reduced half-integers like "1/2", "-3/2", "7/2".
  const m = /^(-?\d+)\/(\d+)$/.exec(s);
  if (m === null) {
    throw new Error(
      `parseFractionToRational: malformed fraction '${s}'. ` +
      `suggestion: half-integer corpus rows are supposed to emit "[-]a/b" reduced form.`
    );
  }
  const a = BigInt(m[1]!);
  const b = BigInt(m[2]!);
  if (b === 0n) throw new Error(`parseFractionToRational: zero denominator in '${s}'`);
  const g = gcd(a < 0n ? -a : a, b);
  return { num: a / g, den: b / g };
}

function gcd(a: bigint, b: bigint): bigint {
  while (b !== 0n) {
    [a, b] = [b, a % b];
  }
  return a;
}

// -----------------------------------------------------------------------------
// Corpus-value → Wolfram-expression conversion
// -----------------------------------------------------------------------------

/** Convert a corpus ν string (driven by `nu_kind`) into a Wolfram WL expression. */
function nuToWlExpr(nu: string, nuKind: CorpusInput["nu_kind"]): string {
  // The three nu_kinds are mutually exclusive; the parser dispatches on
  // nu_kind, not on string-shape, so a stray "1.5" labelled as
  // "half-integer" (or vice versa) surfaces as a parser exception with the
  // input id, not a silent wrong-precision evaluation (L1 risk).
  switch (nuKind) {
    case "integer": {
      // Plain int-string. Accept negative ("-3") and positive ("0", "50").
      if (!/^-?\d+$/.test(nu)) {
        throw new Error(`nuToWlExpr: nu_kind=integer but nu='${nu}' is not an integer string`);
      }
      return nu;
    }
    case "half-integer": {
      const r = parseFractionToRational(nu);
      if (r.den === 1n) return r.num.toString();
      return `Rational[${r.num.toString()}, ${r.den.toString()}]`;
    }
    case "decimal": {
      return decimalStringToWl(nu);
    }
  }
}

/** Convert a corpus z (string or {re, im}) into a Wolfram z-expression. */
function zToWlExpr(z: CorpusZ): string {
  if (typeof z === "string") return decimalStringToWl(z);
  const re = decimalStringToWl(z.re);
  const im = decimalStringToWl(z.im);
  // Always parenthesise both halves so unary-minus binds correctly:
  // "(-Infinity) + (0)*I" is unambiguous; "-Infinity + 0*I" might lex
  // differently depending on operator precedence.
  return `(${re}) + (${im}) * I`;
}

function decimalStringToWl(s: string): string {
  if (s === "NaN") return "Indeterminate";
  if (s === "Infinity") return "Infinity";
  if (s === "-Infinity") return "-Infinity";
  const r = parseDecimalToRational(s);
  if (r.den === 1n) return r.num.toString();
  return `Rational[${r.num.toString()}, ${r.den.toString()}]`;
}

// -----------------------------------------------------------------------------
// Per-input Wolfram code emission (head-dispatch table)
// -----------------------------------------------------------------------------
//
// The four canonical Bessel heads map directly to Wolfram symbols. The two
// scaled variants are computed by composition:
//
//   BesselIScaled(ν, z) := e^{-|Re z|} · BesselI(ν, z)        (analytic continuation;
//                                                              for real positive z reduces to
//                                                              e^{-z} · I_ν(z))
//   BesselKScaled(ν, z) := e^{z} · BesselK(ν, z)               (for real positive z; analytic
//                                                              elsewhere)
//
// The corpus uses these scaled heads exclusively in T3/T6/T10 at large
// real z where the unscaled value would over/underflow float64. At
// arbitrary precision Wolfram does not overflow/underflow, so the
// composition is just a multiplication by the appropriate exponential.

const KNOWN_HEADS = new Set([
  "BesselJ", "BesselY", "BesselI", "BesselK", "BesselIScaled", "BesselKScaled",
]);

/** Build the Wolfram expression body for `head[ν, z]`. */
function wlBodyFor(head: string, nuExpr: string, zExpr: string): string {
  switch (head) {
    case "BesselJ": return `BesselJ[${nuExpr}, ${zExpr}]`;
    case "BesselY": return `BesselY[${nuExpr}, ${zExpr}]`;
    case "BesselI": return `BesselI[${nuExpr}, ${zExpr}]`;
    case "BesselK": return `BesselK[${nuExpr}, ${zExpr}]`;
    case "BesselIScaled": {
      // e^{-|Re z|} · I_ν(z). For real z this is the canonical scaled-I.
      // For complex z the |Re z| factor matches the AMOS ZBESI scaled
      // convention.
      return `Exp[-Abs[Re[${zExpr}]]] * BesselI[${nuExpr}, ${zExpr}]`;
    }
    case "BesselKScaled": {
      // e^{z} · K_ν(z). Wolfram has no native `BesselKScaled` symbol;
      // composition at 60 working digits is the correct path.
      return `Exp[${zExpr}] * BesselK[${nuExpr}, ${zExpr}]`;
    }
    default: throw new Error(`wlBodyFor: unknown head '${head}'`);
  }
}

// -----------------------------------------------------------------------------
// Build the batch .wls program
// -----------------------------------------------------------------------------
//
// The preamble defines three Wolfram functions:
//
//   ClassifyResult[r] — buckets a numeric-evaluation result into:
//     INEXACT-NUMERIC | EXACT-NUMERIC | INDETERMINATE | POS-INFINITY |
//     NEG-INFINITY | COMPLEX-INFINITY | REFUSE.
//     `REFUSE` covers any expression that did NOT collapse to a number
//     after `N[…, 60]` — typically because the head saw a symbolic
//     argument like `Infinity` that has no numeric representation
//     (e.g. `BesselI[0, Infinity]` returns itself unevaluated).
//
//   FormatNumeric[x] — stringifies x via InputForm then normalises:
//     `BT<prec>.*^<exp>` → `e<exp>`  (L_carryover mitigation; was the G2a bug)
//     `BT<prec>.<end>`   → `<end>`   (precision-suffix strip)
//     Both regexes are applied in order; strip-exponent first so the
//     trailing-strip doesn't shave the mantissa.
//
//   PrintRecord[id, expr, headStr, zStr] — applies Quiet[N[expr, 60]],
//     post-processes Underflow[]/Overflow[] wrappers, classifies, and
//     prints one delimited line per input. The header `__VERSIONS__|...`
//     captures the kernel version before any numerics so even total
//     failure preserves the provenance.
//
// Delimiter: pipe `|`. Status field is one of the classifier strings.
// Re/Im fields are FormatNumeric strings (real for scalar outputs;
// im="0" when the output is real-valued). Token field captures the raw
// pre-N[] symbolic form when the classifier says REFUSE — this is the
// `wolfram_returned_token` per the orchestrator's schema.
//
// One subtle quote-escape note: the regex literals look over-escaped
// because they are. Wolfram's string parser interprets backslash-escape
// sequences inside "..." BEFORE the resulting string reaches
// RegularExpression[]; so `"\\\\*"` in the JS template-literal source
// emits `"\\*"` on the wire, which Wolfram parses to `"\*"` for the
// regex engine — exactly what we want for a literal asterisk in the
// regex. The backtick (codepoint 96) is not a regex metacharacter and
// needs no escaping on the regex side, only the JS-template-literal
// "\\`" escape so it doesn't terminate the template literal.

const BATCH_PREAMBLE = `
(* Generated by bench/besselj-anchor/oracles/wolfram/adapter.ts. *)

(* Disable Wolfram's default Print line-wrapping. The default $PageWidth ~ 78 *)
(* chops 60-decimal outputs across multiple physical lines and breaks the    *)
(* consumer's line-oriented parser. Infinity = no wrapping ever.              *)
$PageWidth = Infinity;

(* Classifier: dispatches on the numeric-evaluation result so unevaluated   *)
(* symbolic forms (e.g. BesselI[0, Infinity], a limit Wolfram doesn't       *)
(* volunteer numerically) refuse cleanly rather than echoing a non-number   *)
(* as if it were one.                                                       *)
ClassifyResult[r_] := Which[
  r === Indeterminate, "INDETERMINATE",
  r === Infinity, "POS-INFINITY",
  r === -Infinity, "NEG-INFINITY",
  r === ComplexInfinity || Head[r] === DirectedInfinity, "COMPLEX-INFINITY",
  IntegerQ[r] || Head[r] === Rational, "EXACT-NUMERIC",
  InexactNumberQ[r], "INEXACT-NUMERIC",
  True, "REFUSE"
];

(* FormatNumeric: rewrite Wolfram's InputForm of an arb-prec number to a    *)
(* standard-scientific or plain-decimal string. See top-of-file commentary  *)
(* for the L_carryover / L11 motivation.                                     *)
FormatNumeric[x_] := StringReplace[
  ToString[x, InputForm],
  {RegularExpression["\`[0-9.]+\\\\*\\\\^"] -> "e",
   RegularExpression["\`[0-9.]+$"] -> ""}
];

(* PrintRecord emits one line per input. Format:                            *)
(*   id|STATUS|REorVAL|IM|TOKEN                                              *)
(* TOKEN is the raw symbolic form when STATUS=REFUSE (so the consumer can   *)
(* capture wolfram_returned_token honestly); empty otherwise.               *)
(*                                                                          *)
(* Underflow[]/Overflow[] handling: for inputs whose magnitude pushes the   *)
(* kernel past $MaxExtraPrecision, Wolfram emits a wrapper symbol like     *)
(* '1 - Underflow[]' instead of a limit. We replace Underflow[] -> 0 and    *)
(* Overflow[] -> Infinity and re-evaluate. The unmolested pre-N form is    *)
(* captured as TOKEN when this triggers a REFUSE.                          *)
PrintRecord[id_, expr_] := Module[{rawN, replaced, cls, reStr, imStr, tokenStr},
  rawN = Quiet[N[expr, 60]];
  replaced = rawN /. {Underflow[] -> 0, Overflow[] -> Infinity};
  replaced = Quiet[N[replaced, 60]];
  cls = ClassifyResult[replaced];
  Which[
    cls === "INEXACT-NUMERIC",
      reStr = FormatNumeric[Re[replaced]];
      imStr = FormatNumeric[Im[replaced]];
      Print[StringJoin[id, "|INEXACT|", reStr, "|", imStr, "|"]],
    cls === "EXACT-NUMERIC",
      Print[StringJoin[id, "|EXACT|", FormatNumeric[replaced], "|0|"]],
    cls === "REFUSE",
      (* Capture the symbolic token (e.g. "BesselI[0, Infinity]") for the *)
      (* consumer; truncate to 200 chars defensively (a runaway symbolic *)
      (* form could blow up the record line otherwise).                  *)
      tokenStr = ToString[replaced, InputForm];
      If[StringLength[tokenStr] > 200, tokenStr = StringTake[tokenStr, 200] <> "..."];
      Print[StringJoin[id, "|REFUSE||0|", tokenStr]],
    True,
      Print[StringJoin[id, "|", cls, "||0|"]]
  ]
];

(* Header: capture versions BEFORE any numerical work so the version probe *)
(* still succeeds even if every evaluation aborts.                          *)
Print[StringJoin["__VERSIONS__|", ToString[$VersionNumber], "|", $Version]];
`.trim() + "\n";

function buildBatchProgram(inputs: ReadonlyArray<CorpusInput>): string {
  const lines: string[] = [BATCH_PREAMBLE];
  for (const inp of inputs) {
    if (!KNOWN_HEADS.has(inp.head)) {
      throw new Error(
        `buildBatchProgram: corpus input ${inp.id} has unknown head '${inp.head}'. ` +
        `suggestion: extend KNOWN_HEADS / wlBodyFor in adapter.ts to support it.`
      );
    }
    const nuExpr = nuToWlExpr(inp.nu, inp.nu_kind);
    const zExpr = zToWlExpr(inp.z);
    const body = wlBodyFor(inp.head, nuExpr, zExpr);
    // ids contain only [A-Za-z0-9-] which is safe inside a Wolfram String[].
    lines.push(`PrintRecord["${inp.id}", ${body}];`);
  }
  return lines.join("\n");
}

// -----------------------------------------------------------------------------
// wolframscript stdout parser
// -----------------------------------------------------------------------------
//
// Belt-and-suspenders against any regression in the .wls preamble: even
// though `FormatNumeric` should strip every backtick, the TS-side
// `stripPrecisionSuffix` re-applies the strip and tolerates a trailing
// dot (e.g. `1.` → `1`). The .wls preamble does the load-bearing rewrite
// (`*^` → `e`); this helper is the just-in-case shaver.

function stripPrecisionSuffix(s: string): string {
  const tick = s.indexOf("`");
  let body = tick >= 0 ? s.slice(0, tick) : s;
  if (body.endsWith(".")) body = body.slice(0, -1);
  return body;
}

interface ParsedRecord {
  id: string;
  status: "INEXACT" | "EXACT" | "INDETERMINATE" | "POS-INFINITY" | "NEG-INFINITY" | "COMPLEX-INFINITY" | "REFUSE";
  re: string;
  im: string;
  token: string;
}

function parseBatchStdout(stdout: string): {
  versions: { number: string; long: string };
  records: ParsedRecord[];
} {
  const records: ParsedRecord[] = [];
  let versions: { number: string; long: string } | null = null;
  for (const rawLine of stdout.split("\n")) {
    const line = rawLine.replace(/\r$/, "");
    if (line === "") continue;
    if (line.startsWith("__VERSIONS__|")) {
      const parts = line.split("|");
      if (parts.length < 3) {
        throw new Error(`parseBatchStdout: malformed __VERSIONS__ line: ${line}`);
      }
      versions = { number: parts[1] ?? "", long: parts.slice(2).join("|") };
      continue;
    }
    // Per-record lines: id|STATUS|RE|IM|TOKEN  (5 fields, last possibly empty).
    // TOKEN may contain '|' if Wolfram's symbolic form embeds one (defensive
    // re-join past index 4).
    const parts = line.split("|");
    if (parts.length < 5) {
      if (/::/.test(line)) {
        // Wolfram diagnostic (e.g. `General::stop`, `BesselK::overflow`).
        // Surface on stderr but don't abort — the per-input classifier
        // still produces a record for the real input.
        process.stderr.write(`[wolfram-msg] ${line}\n`);
        continue;
      }
      throw new Error(`parseBatchStdout: malformed record line: '${line}'`);
    }
    const [id, status, re, im] = parts as [string, ParsedRecord["status"], string, string];
    const token = parts.slice(4).join("|");
    const valid = new Set([
      "INEXACT", "EXACT", "INDETERMINATE", "POS-INFINITY", "NEG-INFINITY",
      "COMPLEX-INFINITY", "REFUSE",
    ]);
    if (!valid.has(status)) {
      throw new Error(`parseBatchStdout: unknown status '${status}' in line '${line}'`);
    }
    records.push({ id, status, re: re ?? "", im: im ?? "", token });
  }
  if (versions === null) {
    throw new Error(
      `parseBatchStdout: did not find __VERSIONS__ line in wolframscript stdout. ` +
      `suggestion: wolframscript may have failed before reaching the version probe; ` +
      `check stderr for an early-abort diagnostic.`
    );
  }
  return { versions, records };
}

// -----------------------------------------------------------------------------
// Wolframscript resolver — mirrors the spawnBun resolver shape (ADR-0001)
// -----------------------------------------------------------------------------

let cachedWolframscript: string | null = null;

function resolveWolframscript(): string {
  if (cachedWolframscript !== null) return cachedWolframscript;
  const fromEnv = process.env["WOLFRAMSCRIPT_BIN"];
  let initial: string | null = fromEnv && fromEnv.length > 0 ? fromEnv : null;
  if (initial === null) {
    const path = process.env["PATH"] ?? "";
    for (const dir of path.split(delimiter)) {
      if (!dir) continue;
      const candidate = join(dir, "wolframscript");
      if (existsSync(candidate)) { initial = candidate; break; }
    }
  }
  if (initial === null) {
    throw new Error(
      `resolveWolframscript: cannot find 'wolframscript' on PATH and ` +
      `WOLFRAMSCRIPT_BIN is unset. ` +
      `suggestion: install Wolfram Mathematica or set WOLFRAMSCRIPT_BIN to ` +
      `the absolute path.`
    );
  }
  let real: string;
  try { real = realpathSync(initial); }
  catch (e) {
    throw new Error(`resolveWolframscript: '${initial}' does not resolve via realpath: ${(e as Error).message}`);
  }
  cachedWolframscript = real;
  return real;
}

interface SpawnResult { code: number; stdout: string; stderr: string; }

async function spawnWolframscriptVersion(): Promise<string> {
  const bin = resolveWolframscript();
  const proc = Bun.spawn([bin, "-version"], { stdout: "pipe", stderr: "pipe", stdin: "ignore" });
  const stdout = await new Response(proc.stdout).text();
  const stderr = await new Response(proc.stderr).text();
  const code = await proc.exited;
  if (code !== 0) {
    throw new Error(
      `spawnWolframscriptVersion: '${bin} -version' exited ${code}; stderr: ${stderr.trim()}. ` +
      `suggestion: confirm the Wolfram kernel is activated (wolframscript -code 'Print[1+1]').`
    );
  }
  return stdout.trim();
}

async function spawnWolframscriptFile(scriptPath: string): Promise<SpawnResult> {
  const bin = resolveWolframscript();
  const proc = Bun.spawn([bin, "-file", scriptPath], {
    stdout: "pipe", stderr: "pipe", stdin: "ignore",
  });
  const [stdout, stderr, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ]);
  return { code, stdout, stderr };
}

// -----------------------------------------------------------------------------
// Status → result-record conversion
// -----------------------------------------------------------------------------
//
// Maps the .wls classifier's labels into the orchestrator's
// `status ∈ {success, limit, refused, error}` schema with the
// `wolfram_returned_token` field carrying the symbolic form when honest.
//
// The classification rules:
//
//   INEXACT-NUMERIC → success, value = scalar string (real input) or {re,im}
//                     (complex input — preserves the corpus's input shape).
//   EXACT-NUMERIC   → success, value = integer/rational string. Wolfram
//                     returns "0", "1", "2" for exact limits (e.g.
//                     J_0(0)=1).
//   POS-INFINITY    → limit, value = null, token = "Infinity".
//   NEG-INFINITY    → limit, value = null, token = "-Infinity".
//   COMPLEX-INFINITY→ limit, value = null, token = "ComplexInfinity".
//   INDETERMINATE   → limit, value = null, token = "Indeterminate". This
//                     covers (a) NaN-input propagation and (b) the
//                     0·Infinity composition that the scaled-I or scaled-K
//                     occasionally produces at the edge of representation.
//   REFUSE          → limit if the symbolic form is a known-bounded Bessel
//                     symbol (e.g. "BesselI[0, Infinity]" — Wolfram declines
//                     to volunteer numerically but the function HAS a
//                     finite-or-infinite limit). Otherwise, refused.
//
// "error" is reserved for adapter-side failures (parse, spawn) — Wolfram
// itself never returns an error result through this pipeline; the worst
// case is a REFUSE.

function buildResultRecord(
  inp: CorpusInput,
  parsed: ParsedRecord,
  elapsedMs: number,
): ResultRecord {
  const isComplexInput = typeof inp.z !== "string";
  switch (parsed.status) {
    case "INEXACT": {
      const re = stripPrecisionSuffix(parsed.re);
      const im = stripPrecisionSuffix(parsed.im);
      const imIsZero = im === "0" || /^-?0(\.0+)?$/.test(im);
      // If the *input* was real and the imaginary part is exactly zero, emit
      // a scalar string. Otherwise emit {re, im} so downstream comparators
      // preserve the input shape.
      if (!isComplexInput && imIsZero) {
        return {
          input_id: inp.id,
          status: "success",
          value: re,
          wolfram_returned_token: null,
          elapsed_ms: elapsedMs,
        };
      }
      return {
        input_id: inp.id,
        status: "success",
        value: { re, im },
        wolfram_returned_token: null,
        elapsed_ms: elapsedMs,
      };
    }
    case "EXACT": {
      // Exact integers / rationals: e.g. J_0(0)=1, Y_0(0)=-Infinity (caught
      // by NEG-INFINITY branch), J_n(0)=0 for n>=1. Preserve as a scalar
      // string for real inputs, {re,im} for complex.
      const v = parsed.re;
      if (!isComplexInput) {
        return {
          input_id: inp.id,
          status: "success",
          value: v,
          wolfram_returned_token: null,
          elapsed_ms: elapsedMs,
        };
      }
      return {
        input_id: inp.id,
        status: "success",
        value: { re: v, im: "0" },
        wolfram_returned_token: null,
        elapsed_ms: elapsedMs,
      };
    }
    case "POS-INFINITY":
      return {
        input_id: inp.id,
        status: "limit",
        value: null,
        wolfram_returned_token: "Infinity",
        elapsed_ms: elapsedMs,
      };
    case "NEG-INFINITY":
      return {
        input_id: inp.id,
        status: "limit",
        value: null,
        wolfram_returned_token: "-Infinity",
        elapsed_ms: elapsedMs,
      };
    case "COMPLEX-INFINITY":
      return {
        input_id: inp.id,
        status: "limit",
        value: null,
        wolfram_returned_token: "ComplexInfinity",
        elapsed_ms: elapsedMs,
      };
    case "INDETERMINATE":
      return {
        input_id: inp.id,
        status: "limit",
        value: null,
        wolfram_returned_token: "Indeterminate",
        elapsed_ms: elapsedMs,
      };
    case "REFUSE": {
      // Wolfram returned a symbolic form (e.g. "BesselI[0, Infinity]").
      // Classify as "limit" — the function HAS a mathematical limit,
      // Wolfram simply declined to volunteer it numerically.
      return {
        input_id: inp.id,
        status: "limit",
        value: null,
        wolfram_returned_token: parsed.token,
        elapsed_ms: elapsedMs,
        notes: "Wolfram declined to numerically evaluate the head at this symbolic argument; " +
               "the limit may exist (e.g. I_0(∞)=∞) but the kernel returns the unevaluated form.",
      };
    }
  }
}

// -----------------------------------------------------------------------------
// Main entry — corpus-load → build .wls → subprocess wolframscript ONCE
// → parse stdout → emit results.json
// -----------------------------------------------------------------------------

async function main(): Promise<void> {
  const here = dirname(fileURLToPath(import.meta.url));
  const corpusPath = join(here, "..", "..", "corpus.json");
  const outputPath = join(here, "results.json");

  // 1. Load corpus.
  const corpusRaw = readFileSync(corpusPath, "utf8");
  const corpus: Corpus = JSON.parse(corpusRaw);
  if (!Array.isArray(corpus.inputs) || corpus.inputs.length === 0) {
    throw new Error(
      `adapter: corpus at ${corpusPath} has no inputs (or is malformed). ` +
      `suggestion: regenerate via 'bun bench/besselj-anchor/generate-corpus.ts'.`
    );
  }

  // 2. Probe wolframscript CLI version up-front (so we record it even if
  //    the batch program itself aborts).
  const cliVersion = await spawnWolframscriptVersion();
  process.stderr.write(`[wolfram-adapter] CLI: ${cliVersion}\n`);
  process.stderr.write(`[wolfram-adapter] inputs in corpus: ${corpus.inputs.length}\n`);

  // 3. Build the batch program and write to a tempfile.
  const program = buildBatchProgram(corpus.inputs);
  const td = mkdtempSync(join(tmpdir(), "wolfram-bessel-oracle-"));
  const scriptPath = join(td, "batch.wls");
  writeFileSync(scriptPath, program, "utf8");
  process.stderr.write(`[wolfram-adapter] batch .wls size: ${program.length} bytes at ${scriptPath}\n`);
  process.stderr.write(`[wolfram-adapter] launching wolframscript -file <batch.wls> (cold-start ~7.6s; per-input ~1.4s; expect ~40min wall-time)\n`);

  // 4. Execute. Time the whole batch.
  const t0 = Date.now();
  let runResult: SpawnResult;
  try {
    runResult = await spawnWolframscriptFile(scriptPath);
  } finally {
    try { rmSync(td, { recursive: true, force: true }); } catch { /* ignore */ }
  }
  const totalElapsed = Date.now() - t0;

  if (runResult.code !== 0) {
    throw new Error(
      `adapter: wolframscript exited with code ${runResult.code}.\n` +
      `stderr (tail):\n${runResult.stderr.slice(-1000)}\n` +
      `suggestion: re-run with WOLFRAMSCRIPT_BIN set to the kernel-script binary, ` +
      `or run the program directly via 'wolframscript -file <scriptPath>' for diagnostics.`
    );
  }

  // 5. Parse.
  const { versions, records } = parseBatchStdout(runResult.stdout);
  process.stderr.write(`[wolfram-adapter] kernel: ${versions.long}\n`);
  process.stderr.write(`[wolfram-adapter] parsed ${records.length} records in ${totalElapsed} ms\n`);

  if (records.length !== corpus.inputs.length) {
    throw new Error(
      `adapter: expected ${corpus.inputs.length} records, got ${records.length}. ` +
      `suggestion: a Wolfram per-input failure may have aborted printing; ` +
      `inspect stderr (above) for the failing input id.`
    );
  }

  // 6. Re-shape: build per-input result records, preserving corpus order.
  const recordById = new Map<string, ParsedRecord>(records.map((r) => [r.id, r]));
  // Amortise total elapsed evenly per-input as a coarse approximation; the
  // batch program does not time individual evaluations to keep the wire
  // format simple.
  const perInputElapsed = Math.round(totalElapsed / corpus.inputs.length);

  const results: ResultRecord[] = corpus.inputs.map((inp) => {
    const parsed = recordById.get(inp.id);
    if (parsed === undefined) {
      throw new Error(
        `adapter: corpus input ${inp.id} missing from wolframscript output. ` +
        `suggestion: a per-input Wolfram diagnostic may have prevented PrintRecord from running; ` +
        `re-execute with diagnostics on for that id.`
      );
    }
    return buildResultRecord(inp, parsed, perInputElapsed);
  });

  // 7. Wrap into the file-level envelope (matches orchestrator schema).
  const totals = {
    success: results.filter((r) => r.status === "success").length,
    refused: results.filter((r) => r.status === "refused").length,
    limit: results.filter((r) => r.status === "limit").length,
    error: results.filter((r) => r.status === "error").length,
  };

  const envelope = {
    oracle_id: "wolfram",
    oracle_version: `Mathematica ${versions.long} / wolframscript ${cliVersion}`,
    generated_at: new Date().toISOString(),
    corpus_seed: 20260517,
    tier: "gold",
    precision_decimals_requested: 60,
    bead: "scientist-workbench-z9fq",
    adr: "0041",
    total_inputs: corpus.inputs.length,
    total_elapsed_ms: totalElapsed,
    notes: [
      "Decimal inputs (both ν and z) are wrapped as Rational[num,den] to dodge the MachinePrecision input-trap (R5 §6 L1).",
      "Half-integer ν is constructed as Rational[a,b] from the corpus's '\"a/b\"' string form (R5 §6 L1, parser-side).",
      "BesselIScaled := Exp[-Abs[Re[z]]]·BesselI[ν,z] and BesselKScaled := Exp[z]·BesselK[ν,z] (Wolfram has no native symbol for these).",
      "Underflow[]→0 and Overflow[]→Infinity replacement applied before classification (R5 §6 L9/L10 belt-and-suspenders; rarely triggers at 60dps).",
      "'limit' status (value=null + wolfram_returned_token=symbolic-form) covers Wolfram's unevaluated symbolic returns (e.g. BesselI[0,Infinity]).",
      "Wolfram emits ~2 noise digits past the declared precision (R5 §6 L11); G8 comparator handles the tier-tolerance band, not this adapter.",
    ],
    totals,
    results,
  };

  writeFileSync(outputPath, JSON.stringify(envelope, null, 2) + "\n", "utf8");
  process.stdout.write(
    `Wrote N=${results.length} results ` +
    `(success=${totals.success}, limit=${totals.limit}, refused=${totals.refused}, error=${totals.error}) ` +
    `in ${totalElapsed}ms -> ${outputPath}\n`
  );
}

if (import.meta.main || import.meta.url === `file://${process.argv[1]}`) {
  main().catch((err) => {
    process.stderr.write(`[wolfram-adapter] FAIL: ${(err as Error).message}\n`);
    process.exitCode = 1;
  });
}
